name: Run BackstopJS test cases # Name of the action
description: This action will archive the test when there is some failure in the backstop test. Also, you can download the result.
author: Ankit Raj
branding:
  icon: 'activity'
  color: 'Blue'
on:
  push:
  schedule: # 23:30 IST == 18:00 UTC
  - cron: "0 18 * * *"
  
  workflow_dispatch:
    branches:
    - master
    
jobs:
  build:
    name: backstop reference
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install backstopjs
        run: npm install --force -g backstopjs
      - name: Create reference screenshot from source site
        run: backstop reference
      - name: Run the test(It will take the screenshot of the given site and will test against reference screenshot)
        run: backstop test
      - name: create a folder
        run: mkdir backstop_data
      - name: Archive HTML Report on failure
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: backstop_data/
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
         # Artifact name
         name: Download report
         # Destination path
         path: backstop_data
      
